name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ eureka-server, user-service, product-service, cart-service, order-service, payment-service ]
    steps:
      - uses: actions/checkout@v4
      - name: Qodana Scan for ${{ matrix.service }}
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: false